-- Customer-supplied material coming in, and our own fabric going out to a job
-- worker and coming back.
--
-- Three documents and one correction.
--
-- `customer_grn` records a customer's own material arriving for us to work on.
-- It is never our stock: every movement it writes carries CUSTOMER_OWNED and
-- the customer's id, which is what keeps it out of the stock value per
-- docs/04-business-rules.md rule 6.5.
--
-- `job_work_challans` and `job_work_returns` record our fabric leaving for an
-- outside unit and coming back. The goods move to a warehouse standing for that
-- unit rather than leaving the ledger, because rule 6.5 says fabric at a job
-- worker is still ours and rule 6.4 says stock always lives in a warehouse.
--
-- The correction is the two columns on `material_requisition_lines`. Without
-- them a requisition for a customer's fabric would be issued out of our own
-- balance of the same cloth: theirs would sit in the godown unusable and ours
-- would quietly go missing. They default to OWNED, which is what every line
-- written before today meant.
--
-- Written by hand for the same reason as 20260916104500 and 20260917100000:
-- the live database carries tables and columns from unmerged branches —
-- purchase enquiries, purchase returns, BOM costing — that `migrate dev` wants
-- to drop. This file was generated by diffing main's schema against this one,
-- so it holds only its own statements. Verified before applying: no DROP, no
-- DELETE, no TRUNCATE. It creates six tables, one enum, one enum value, two
-- nullable-or-defaulted columns, eight indexes and twenty-one foreign keys,
-- and it touches no existing row.

-- CreateEnum
CREATE TYPE "JobWorkStatus" AS ENUM ('SENT', 'PARTLY_BACK', 'CLOSED', 'CANCELLED');

-- AlterEnum
ALTER TYPE "TransactionType" ADD VALUE 'CUSTOMER_MATERIAL';

-- AlterTable
ALTER TABLE "material_requisition_lines" ADD COLUMN     "ownerCustomerId" TEXT,
ADD COLUMN     "ownership" "StockOwnership" NOT NULL DEFAULT 'OWNED';

-- CreateTable
CREATE TABLE "customer_grn" (
    "id" TEXT NOT NULL,
    "grnNumber" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "soId" TEXT,
    "receiptDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "challanNumber" TEXT,
    "challanDate" TIMESTAMP(3),
    "gateEntryNumber" TEXT,
    "gateEntryDate" TIMESTAMP(3),
    "vehicleNo" TEXT,
    "transporter" TEXT,
    "warehouseId" TEXT NOT NULL,
    "notes" TEXT,
    "receivedById" TEXT,
    "cancelledAt" TIMESTAMP(3),
    "cancelledById" TEXT,
    "cancelReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "customer_grn_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "customer_grn_lines" (
    "id" TEXT NOT NULL,
    "grnId" TEXT NOT NULL,
    "itemId" TEXT NOT NULL,
    "challanQty" DECIMAL(10,3) NOT NULL,
    "receivedQty" DECIMAL(10,3) NOT NULL,
    "batchNumber" TEXT,
    "markings" TEXT,

    CONSTRAINT "customer_grn_lines_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "job_work_challans" (
    "id" TEXT NOT NULL,
    "challanNumber" TEXT NOT NULL,
    "jobWorkerId" TEXT NOT NULL,
    "challanDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "process" TEXT NOT NULL,
    "fromWarehouseId" TEXT NOT NULL,
    "toWarehouseId" TEXT NOT NULL,
    "expectedBackOn" TIMESTAMP(3),
    "vehicleNo" TEXT,
    "transporter" TEXT,
    "lrNumber" TEXT,
    "notes" TEXT,
    "status" "JobWorkStatus" NOT NULL DEFAULT 'SENT',
    "sentById" TEXT,
    "cancelledAt" TIMESTAMP(3),
    "cancelledById" TEXT,
    "cancelReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "job_work_challans_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "job_work_challan_lines" (
    "id" TEXT NOT NULL,
    "challanId" TEXT NOT NULL,
    "itemId" TEXT NOT NULL,
    "qty" DECIMAL(10,3) NOT NULL,
    "hsnCode" TEXT,
    "unitRate" DECIMAL(10,2),

    CONSTRAINT "job_work_challan_lines_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "job_work_returns" (
    "id" TEXT NOT NULL,
    "returnNumber" TEXT NOT NULL,
    "challanId" TEXT NOT NULL,
    "returnDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "vehicleNo" TEXT,
    "lrNumber" TEXT,
    "theirChallanNo" TEXT,
    "notes" TEXT,
    "receivedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "job_work_returns_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "job_work_return_lines" (
    "id" TEXT NOT NULL,
    "returnId" TEXT NOT NULL,
    "challanLineId" TEXT NOT NULL,
    "consumedQty" DECIMAL(10,3) NOT NULL,
    "itemId" TEXT NOT NULL,
    "receivedQty" DECIMAL(10,3) NOT NULL,
    "wastedQty" DECIMAL(10,3) NOT NULL DEFAULT 0,
    "warehouseId" TEXT NOT NULL,
    "notes" TEXT,

    CONSTRAINT "job_work_return_lines_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "customer_grn_grnNumber_key" ON "customer_grn"("grnNumber");

-- CreateIndex
CREATE INDEX "customer_grn_customerId_idx" ON "customer_grn"("customerId");

-- CreateIndex
CREATE INDEX "customer_grn_receiptDate_idx" ON "customer_grn"("receiptDate");

-- CreateIndex
CREATE UNIQUE INDEX "job_work_challans_challanNumber_key" ON "job_work_challans"("challanNumber");

-- CreateIndex
CREATE INDEX "job_work_challans_jobWorkerId_idx" ON "job_work_challans"("jobWorkerId");

-- CreateIndex
CREATE INDEX "job_work_challans_status_idx" ON "job_work_challans"("status");

-- CreateIndex
CREATE UNIQUE INDEX "job_work_returns_returnNumber_key" ON "job_work_returns"("returnNumber");

-- CreateIndex
CREATE INDEX "job_work_returns_challanId_idx" ON "job_work_returns"("challanId");

-- AddForeignKey
ALTER TABLE "material_requisition_lines" ADD CONSTRAINT "material_requisition_lines_ownerCustomerId_fkey" FOREIGN KEY ("ownerCustomerId") REFERENCES "customers"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_grn" ADD CONSTRAINT "customer_grn_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_grn" ADD CONSTRAINT "customer_grn_soId_fkey" FOREIGN KEY ("soId") REFERENCES "sales_orders"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_grn" ADD CONSTRAINT "customer_grn_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_grn" ADD CONSTRAINT "customer_grn_receivedById_fkey" FOREIGN KEY ("receivedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_grn" ADD CONSTRAINT "customer_grn_cancelledById_fkey" FOREIGN KEY ("cancelledById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_grn_lines" ADD CONSTRAINT "customer_grn_lines_grnId_fkey" FOREIGN KEY ("grnId") REFERENCES "customer_grn"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_grn_lines" ADD CONSTRAINT "customer_grn_lines_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_work_challans" ADD CONSTRAINT "job_work_challans_jobWorkerId_fkey" FOREIGN KEY ("jobWorkerId") REFERENCES "suppliers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_work_challans" ADD CONSTRAINT "job_work_challans_fromWarehouseId_fkey" FOREIGN KEY ("fromWarehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_work_challans" ADD CONSTRAINT "job_work_challans_toWarehouseId_fkey" FOREIGN KEY ("toWarehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_work_challans" ADD CONSTRAINT "job_work_challans_sentById_fkey" FOREIGN KEY ("sentById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_work_challans" ADD CONSTRAINT "job_work_challans_cancelledById_fkey" FOREIGN KEY ("cancelledById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_work_challan_lines" ADD CONSTRAINT "job_work_challan_lines_challanId_fkey" FOREIGN KEY ("challanId") REFERENCES "job_work_challans"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_work_challan_lines" ADD CONSTRAINT "job_work_challan_lines_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_work_returns" ADD CONSTRAINT "job_work_returns_challanId_fkey" FOREIGN KEY ("challanId") REFERENCES "job_work_challans"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_work_returns" ADD CONSTRAINT "job_work_returns_receivedById_fkey" FOREIGN KEY ("receivedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_work_return_lines" ADD CONSTRAINT "job_work_return_lines_returnId_fkey" FOREIGN KEY ("returnId") REFERENCES "job_work_returns"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_work_return_lines" ADD CONSTRAINT "job_work_return_lines_challanLineId_fkey" FOREIGN KEY ("challanLineId") REFERENCES "job_work_challan_lines"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_work_return_lines" ADD CONSTRAINT "job_work_return_lines_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_work_return_lines" ADD CONSTRAINT "job_work_return_lines_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

