-- A customer's own material going back to them unworked: leftover after their
-- order, rejected at inspection, or more than their challan said.
--
-- Until now it could leave our books only by being issued to the floor, or by
-- cancelling the whole receipt it came in on. Neither is a return, and every
-- leftover roll sat on the stock screen under the customer's name for ever.
--
-- Not a purchase return: that sends our goods back to a supplier against their
-- bill. This has no bill and no money; each line moves CUSTOMER_OWNED stock of
-- that customer out of one store.
--
-- Written by hand for the same reason as 20260928140000: the live database
-- carries tables from unmerged branches that `migrate dev` wants to drop. This
-- file was generated by diffing the previous schema against this one, so it
-- holds only its own statements. It creates two tables, three indexes and
-- seven foreign keys, adds the CMR number series, and touches no existing row.
-- No DROP, no DELETE, no TRUNCATE.

-- CreateTable
CREATE TABLE "customer_material_returns" (
    "id" TEXT NOT NULL,
    "returnNumber" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "grnId" TEXT,
    "returnDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "warehouseId" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "vehicleNo" TEXT,
    "transporter" TEXT,
    "lrNumber" TEXT,
    "notes" TEXT,
    "createdById" TEXT,
    "cancelledAt" TIMESTAMP(3),
    "cancelledById" TEXT,
    "cancelReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "customer_material_returns_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "customer_material_return_lines" (
    "id" TEXT NOT NULL,
    "returnId" TEXT NOT NULL,
    "itemId" TEXT NOT NULL,
    "qty" DECIMAL(10,3) NOT NULL,
    "hsnCode" TEXT,
    "notes" TEXT,

    CONSTRAINT "customer_material_return_lines_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "customer_material_returns_returnNumber_key" ON "customer_material_returns"("returnNumber");

-- CreateIndex
CREATE INDEX "customer_material_returns_customerId_idx" ON "customer_material_returns"("customerId");

-- CreateIndex
CREATE INDEX "customer_material_returns_returnDate_idx" ON "customer_material_returns"("returnDate");

-- AddForeignKey
ALTER TABLE "customer_material_returns" ADD CONSTRAINT "customer_material_returns_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_material_returns" ADD CONSTRAINT "customer_material_returns_grnId_fkey" FOREIGN KEY ("grnId") REFERENCES "customer_grn"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_material_returns" ADD CONSTRAINT "customer_material_returns_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_material_returns" ADD CONSTRAINT "customer_material_returns_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_material_returns" ADD CONSTRAINT "customer_material_returns_cancelledById_fkey" FOREIGN KEY ("cancelledById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_material_return_lines" ADD CONSTRAINT "customer_material_return_lines_returnId_fkey" FOREIGN KEY ("returnId") REFERENCES "customer_material_returns"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_material_return_lines" ADD CONSTRAINT "customer_material_return_lines_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- Numbering for the return: CMR-2627-0001. Written for every company that has
-- no CMR series yet, so re-running it is harmless.
INSERT INTO "number_series" (
  "id", "companyId", "docType", "prefix", "separator",
  "financialYear", "lastNumber", "padding", "isActive"
)
SELECT
  gen_random_uuid()::text,
  c."id",
  'CMR',
  'CMR',
  '-',
  COALESCE(NULLIF(c."currentFY", ''), '2627'),
  0,
  4,
  true
FROM "company" c
WHERE NOT EXISTS (
  SELECT 1 FROM "number_series" ns
  WHERE ns."companyId" = c."id" AND ns."docType" = 'CMR'
);
